image_size = 512
batch_size = 8
device = "cuda"
test = false
num_layers = 8
resnet_layers = 2
hidden_dim = 768
mlp_dim = 4096
num_heads = 12
dropout_rate = 0.1
patch_size = 32
num_patches = 256
num_channels = 3
patching_elements = 3072
final_resnet_output_dim = 2048
num_classes = 2
learning_rate = 3e-5
model_path = "models/vit2.pth"
xgb_model_path = "models/vit2.xgb"
large_xgb_model_path = "models-130M-20ep-base/vit2.xgb"
densenet_model_path = "models/densenet121.pth"
data_dir = "dataset/"
num_epochs = 20
seed = 42
